### PR TITLE
Pypad Glasscoder modification

### PR DESCRIPTION
**Pull request by workino**
Hello Fred i did some modification to the pypad glasscoder script. Now it will not stop to work if utf8 characters  found.

I also moved from pycurl to requests is more flexible with utf json.
I cleaned also the the json.
The problem now look like glasscoder still is sending strange characters to icecast server like:
Coez - La musica non c'Ã¨

The post is sent with correct data (utf-8) 

Regards
Gabriele

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
I suspect that we have an issue in the core code in ```glasscoder(1)``` with processing UTF-8 for ICY protocols. Let me work that problem first.

**Comment by ElvishArtisan** [comment]
I've just fixed multiple UTF-8 processing bugs for both ICY and ICE protocols (see 4ad5ee8, ec424c6 and 71e9e12. We should now be UTF-8 clean on both protocols.

Interestingly, current IceCast (v2.4.4) does itself have problems with displaying multibyte UTF-8 on its web interface, although the actual stream metadata is transmitted correctly.

**Comment by ElvishArtisan** [comment]
This seems to work well.

One question: do we still need pycurl? (I still see an 'import pycurl' in the plug-in source).

Also, please add an entry in 'ChangeLog' to describe your changes.

**Comment by workino** [comment]
Hello Fred,
u are right we don't need any more that import, i removed in my last update.
Added also some lines in Changelog how u suggested.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
